apiVersion: v1
kind: Service
metadata:
  name: dental-care-service
spec:
  selector:
    app: dental-care # select the dental-care pod and expose
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dental-care-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dental-care
  template:
    metadata:
      labels:
        app: dental-care # label by which pod can be selected
    spec:
      containers:
        - name: dental-care-api
          image: gomurali/k8s-dental-care:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://admin:d3nt4Lcar3@dental-care-mongodb-clu.uthghds.mongodb.net/dental-care?retryWrites=true&w=majority"
            - name: JWT_SECRET
              value: "DENTALCARE"