apiVersion: v1
kind: Service
metadata:
  name: dentalcare-service
spec:
  selector:
    app: dentalcare # select the users pod and expose
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dentalcare-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dentalcare
  template:
    metadata:
      labels:
        app: dentalcare # label by which pod can be selected
    spec:
      containers:
        - name: dentalcare-app-container
          image: audiph/k8s-dentalcare-app:latest