apiVersion: v1
kind: Service
metadata:
  name: dentalcareapi-service
spec:
  selector:
    app: dentalcareapi # select the dentalcareapi pod and expose
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dentalcareapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dentalcareapi
  template:
    metadata:
      labels:
        app: dentalcareapi # label by which pod can be selected
    spec:
      containers:
        - name: dentalcareapi-api
          image: audiph/k8s-dentalcareapi:latest
          env:
            - name: MONGODB_CONNECTION_URI
              value: "mongodb+srv://admin:d3nt4Lcar3@dental-care-mongodb-clu.uthghds.mongodb.net/dental-care?retryWrites=true&w=majority"
            - name: JWT_SECRET
              value: "DENTALCARE"